Mystery error when converting to Excel for ...projects... spreadsheet
When the file is called iati-activities.projects.fods, the conversion to Excel results in an error. For other names, it seems to work fine.

Error: Please verify input parameters... (SfxBaseModel::impl_store <file:///workspace/output/iati-activities.projects.xlsx> failed: 0x11b(Error Area:Io Class:Abort Code:27))